version: "3.8"
services:

  neo4j:
    image: neo4j:latest
    container_name: 'neo4j-db'
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure

  mongo-db:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db