version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8081:8081
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  authentication-service:
    image: authentication-service:compose_build
    build:
      context: ./authenticationService
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}

  user-service:
    image: user-service:compose_build
    build:
      context: ./userService
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}

  media-content-service:
    image: media-content-service:compose_build
    build:
      context: ./mediaContentService
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${MEDIA_CONTENT_SERVICE_PORT}

  follow-service:
    image: follow-service:compose_build
    build:
      context: ./followService
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${FOLLOW_SERVICE_PORT}

  notification-service:
    image: notification-service:compose_build
    build:
      context: ./notificationService
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${NOTIFICATION_SERVICE_PORT}

networks:
  backend:
    name: nistagram-backend
    driver: bridge